[package]
name = "sphere-intersect"
version = "0.1.0"
authors = ["Dale Vaillancourt <dalev@alum.wpi.edu>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[profile.release]
panic = "abort"
lto = true

[dependencies]
ocaml-sys = "0.22"
